// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arc': string;
  'badge': string;
  'badgeContent': string;
  'breakerIcon': string;
  'capped': string;
  'deepsight': string;
  'elemental': string;
  'engram': string;
  'fullstack': string;
  'kinetic': string;
  'masterwork': string;
  'quality': string;
  'solar': string;
  'stasis': string;
  'strand': string;
  'void': string;
}
export const cssExports: CssExports;
export = cssExports;
